server:
  # 8004表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8004
spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:6001/springcloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: 192.168.0.133:2181,192.168.0.133:2182,192.168.0.133:2183
      discovery:
        instance-host: ${spring.cloud.client.ip-address}
mybatis:
  mapper-locations: classpath:mapper/*.xml